Blogger/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static


from blogapp.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Home, name="home"),
    path('about/', About, name="about"),
    path('foods/', Foods, name="foods"),
    path('lifestyle/',Lifestyle, name="lifestyle"),
    path('contact/', Contact, name="contact"),
    path('login',Login, name="login"),
    path('logout/',Logout, name="logout"),
    path('signup/', Signup, name="signup"),
    path('blog_detail/<int:bid>/', BlogDetail, name="detail"),
    path('category_detail/<int:cid>/', categortyBlog, name="cateblog"),
    path('userpanel/', UserPanel, name="userpanel" ),
    path('blog_delete/<int:bid>/', DeleteBlog, name="delete"),
    path('addblog/', AddBlog, name="addblog"),
    path('edit_profile', Editprofile, name="editprofile"),
    path('change_password', Changepassword, name="changepassword"),
    path('like_blog/<int:bid>/', BlogLike, name="like"),
    path('comment_blog/<int:bid>/', BlogComment, name="comment"),

    ## eamil gateway ##

    path('gateway/', Gateway, name = "gateway"),
    path('email_gateway/', SendMail, name = "email"), 




]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blogapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
# username password firstname lastname email userimage aboutyou

class UserDetail(models.Model):
    usr = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    userimage = models.FileField(null=True)
    aboutyou = models.TextField(null=True)

    def __str__(self):
        return self.usr.username

#category user title short long  image date

class Category(models.Model):
     name = models.CharField(max_length=100, null=True)

     def __str__(self):
         return self.name

class BlogModel(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
    usr = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=100, null=True)
    short = models.TextField(null=True)
    long = models.TextField(null=True)
    image = models.FileField(null=True)
    date = models.DateField(null=True)

    def __str__(self):
        return self.title

class LikeBlog(models.Model):
    blog = models.ForeignKey(BlogModel,on_delete=models.CASCADE, null=True)
    usr = models.ForeignKey(UserDetail,on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.blog.title +"--"+ self.usr.usr.username

class CommentBLog(models.Model):
    blog = models.ForeignKey(BlogModel,on_delete=models.CASCADE,null=True)
    usr = models.ForeignKey(UserDetail,on_delete=models.CASCADE,null=True)
    comment = models.TextField(null=True)
    commentdate = models.DateField(null=True)

    def __str__(self):
        return self.blog.title +"--"+ self.usr.usr.username

blogapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from blogapp.models import *
from datetime import date
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout

def Home(request):
    allblogs = BlogModel.objects.all()
    lastblog = allblogs[len(allblogs)-1:][0]
    reverseblog = allblogs[::-1]
    recentfour = reverseblog[1:5]
    d = {"allblogs":allblogs, "lastblog":lastblog, "recentfour":recentfour}
    return render(request, 'index.html', d)

def About(request):
    allcategory = Category.objects.all()

    d = {"allcategory":allcategory}
    return render(request, 'about.html', d)

def Foods(request):
    return render(request, 'foods.html')

def Lifestyle(request):
    return render(request, 'lifestyle.html')

def Contact(request):
    return render(request, 'contact.html')


def Login(request):
    error = False
    if request.method == "POST":
        datadict = request.POST
        username = datadict['username']
        password = datadict['pwd']

        user = authenticate(username = username, password = password)
        if user:
            login(request,user)
            return redirect("home")
        else:
            error = True

    d = {"error":error}
    return render(request, 'login.html', d)

def Logout(request):
    logout(request)
    return redirect("home")

def Signup(request):
    error = False
    if request.method == 'POST':
        datadict = request.POST
        username = datadict['username']
        password = datadict['pwd']
        firstname = datadict['firstname']
        lastname = datadict['lastname']
        email = datadict['email']
        img = request.FILES['profileimg']
        aboutyou = datadict['aboutyou']
        
        #check username same or not
        data = User.objects.filter(username = username)
        if data:
            error = True
        else:
            user = User.objects.create_user(username = username, password = password, first_name = firstname, 
                                            last_name = lastname, email = email)
            UserDetail.objects.create(usr = user, userimage = img, aboutyou = aboutyou) 
            return redirect('login')

    d = {"error":error}
    return render(request, 'signup.html', d)

def BlogDetail(request, bid):
    blog = BlogModel.objects.get(id = bid)
    usrdetail = UserDetail.objects.get(usr = blog.usr)
    allcomments = CommentBLog.objects.filter(blog = blog)
    allcategory = Category.objects.all()
    d = { "blog":blog, "user":usrdetail, "allcategory":allcategory, "allcomments":allcomments }
    return render(request, 'single.html', d)

def categortyBlog(request, cid):
    allcategory = Category.objects.all()
    catedata = Category.objects.get(id = cid)
    cateblog = BlogModel.objects.filter(category = catedata)
    d = {"cateblog":cateblog, "catedata":catedata, "allcategory":allcategory}
    return render(request, 'category_blog.html', d)

def UserPanel(request):
    cateblog = BlogModel.objects.filter(usr = request.user)
    udetail = UserDetail.objects.get(usr = request.user)
    d = {"cateblog":cateblog, "udetail":udetail}
    return render(request, "userpanel.html", d)

def DeleteBlog(request, bid):
    blog = BlogModel.objects.get(id = bid)
    blog.delete()
    return redirect("userpanel")

### when user create new blog they get mail ###

def SenddynamicMail(to_mail,sub,blogdata):
   
    from_mail = settings.EMAIL_HOST_USER
    to_mail = to_mail
    sub = sub
    msg = EmailMultiAlternatives(sub,'',from_mail,[to_mail])
    d = {"title":blogdata.title,"dec":blogdata.short,
            "username":blogdata.usr.first_name}
    html = get_template('addblogmail.html').render(d)
    msg.attach_alternative(html, 'text/html')
    msg.send()
    

def AddBlog(request):
    allcat = Category.objects.all()
    if request.method == "POST":
        datadict = request.POST
        title = datadict["title"]
        short = datadict["short"]
        long = datadict["long"]
        blogimg = request.FILES["blogimg"]
        cid = datadict["cid"]
        catdata = Category.objects.get(id = cid)
        usr = request.user
        todaydate = date.today() 
        blogdata = BlogModel.objects.create(category = catdata, usr = usr, title = title,
                                short = short, long = long, image = blogimg, date = todaydate)
        
        SenddynamicMail(request.user.email,"NEW BLOG CREATED", blogdata)

        return redirect('userpanel')

    d = {"allcat":allcat}
    return render(request,'addblog.html', d)


def Editprofile(request):
    details = UserDetail.objects.get(usr = request.user)
    if request.method == 'POST':
        datadict = request.POST
        firstname = datadict['firstname']
        lastname = datadict['lastname']
        email = datadict['email']
        try:
            img = request.FILES['profileimg']
            details.userimage = img
            details.save()
        except KeyError:
            pass

        aboutyou = datadict['aboutyou']
        user = request.user 
        user.first_name = firstname
        user.last_name = lastname
        user.email = email
        user.save()
        details.aboutyou = aboutyou
        details.save()
        return redirect('userpanel')

    d = { "userdetail":details}

    return render(request,'editprofile.html',d)

def Changepassword(request):
    error = False
    if request.method == "POST":
        datadict = request.POST
        oldpwd = datadict['oldpwd']
        newpwd = datadict['newpwd']
        user = authenticate(username = request.user.username, password = oldpwd )
        if user:
            user.set_password(newpwd)
            user.save()
            login(request, user)
            return redirect('userpanel')
        else:
            error = True

    d = {"error":error}
    return render(request, 'changepassword.html', d)

def BlogLike(request,bid):
    if not request.user.is_authenticated:
        return redirect('login')

    blogdata = BlogModel.objects.get(id = bid)
    userdata = UserDetail.objects.get(usr = request.user)
    likedata = LikeBlog.objects.filter(usr = userdata, blog = blogdata)
    if not likedata:
        LikeBlog.objects.create(usr = userdata, blog = blogdata)
    else:
        likedata.delete()

    return redirect('detail',bid)

def BlogComment(request, bid):
    blogdata = BlogModel.objects.get(id = bid)
    userdata = UserDetail.objects.get(usr = request.user)
    comment_date = date.today()
    if request.method == "POST":
        comment = request.POST['comment']
        CommentBLog.objects.create(blog = blogdata, usr = userdata,
                                    commentdate = comment_date, comment = comment)
    return redirect('detail',bid)

### email gateway ###

from django.core.mail import EmailMultiAlternatives
from django.conf import settings
from django.template.loader import get_template

def Gateway(request):
    return render(request,'email_gateway.html')

def SendMail(request):
   
    from_mail = settings.EMAIL_HOST_USER
    to_mail = request.user.email
    sub = 'Confirmation Mail'
    msg = EmailMultiAlternatives(sub,'',from_mail,[to_mail])
    d = {"name":"jainesh"}
    html = get_template('mail_sending.html').render(d)
    msg.attach_alternative(html, 'text/html')
    msg.send()
    return HttpResponse("mail send")

blogapp/templates/about.html
<html>
  <head>
    <title>Blogger - About</title>
  </head>
</html>
 
 {% extends 'nav-footer.html' %}
  {% block sectionData %}
  {% load static %}
    <section class="hero-wrap hero-wrap-2" style="background-image: url({% static 'images/bg_4.jpg' %});">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-center">
          <div class="col-md-9 ftco-animate pb-5 text-center">
            <h1 class="mb-3 bread">About Us</h1>
            <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'home' %}">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>About us<i class="ion-ios-arrow-forward"></i></span></p>
          </div>
        </div>
      </div>
    </section>

		<section class="ftco-counter ftco-section ftco-no-pt ftco-no-pb img" id="section-counter">
    	<div class="container">
    		<div class="row d-flex">
    			<div class="col-md-6 d-flex">
    				<div class="img d-flex align-self-stretch" style="background-image:url({% static 'images/about.jpg' %});"></div>
    			</div>
    			<div class="col-md-6 pl-md-5 py-5">
    				<div class="row justify-content-start pb-3">
		          <div class="col-md-12 heading-section ftco-animate">
		            <h2 class="mb-4"><span>About Stories</span></h2>
		            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia</p>
		          </div>
		        </div>
		    		<div class="row">
					{% for i in allcategory%}	
		          <div class="col-md-6 justify-content-center counter-wrap ftco-animate">
		            <div class="block-18 text-center py-5 bg-light mb-4">
		              <div class="text">
		                <strong class="number" >{{ i.blogmodel_set.count }}</strong>
		                <span>{{ i.name }}</span>
		              </div>
		            </div>
		          </div>
				  {% endfor %}
		          
		          
		         
		        </div>
	        </div>
        </div>
    	</div>
    </section>

    <section class="ftco-section ftco-no-pt ftco-section-about ftco-no-pb bg-darken">
    	<div class="container-fluid">
    		<div class="row">
					<div class="col-sm-6 col-md-6 col-lg-9 order-md-last img py-5" style="background-image: url({% static 'images/bg_3.jpg' %});"></div>

	        <div class="col-sm-6 col-md-6 col-lg-3 py-4 text d-flex align-items-center ftco-animate">
	        	<div class="text-2 py-5 px-4">
	          	<p class="mb-5"><a href="https://vimeo.com/45830194" class="btn-custom popup-vimeo">Watch Video <span class="ion-ios-play ml-4"></span></a></p>
	            <h1 class="mb-5">Roger <br> Bosch</h1>
	            <p class="mb-md-5">A small river named Duden flows by their place and supplies it with the necessary regelialia. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
	            <span class="signature">Roger.Bosch</span>
	          </div>
	        </div>
    		</div>
    	</div>
    </section>
		
		<section class="ftco-subscribe ftco-section bg-light">
      <div class="overlay">
        <div class="container">
          <div class="row d-flex justify-content-center">
            <div class="col-md-8 text-wrap text-center heading-section ftco-animate">
              <h2 class="mb-4"><span>Subcribe to our Newsletter</span></h2>
              <p>A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
              <div class="row d-flex justify-content-center mt-4 mb-4">
                <div class="col-md-8">
                  <form action="#" class="subscribe-form">
                    <div class="form-group d-flex">
                      <input type="text" class="form-control" placeholder="Enter email address">
                      <input type="submit" value="Subscribe" class="submit px-3">
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

{% endblock %}


    

blogapp/templates/addblog.html
<html>
  <head>
    <title>Blogger - Addblog</title>
  </head>
</html>
{% extends 'nav-footer.html '%}
{% load static %}
{% block sectionData %}
<section class="hero-wrap hero-wrap-2" style="background-image: url({% static 'images/bg_4.jpg' %});">
    <div class="overlay"></div>
    <div class="container">
      <div class="row no-gutters slider-text align-items-end justify-content-center">
        <div class="col-md-9 ftco-animate pb-5 text-center">
          <h1 class="mb-3 bread">Add Blog</h1>
          <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'home' %}">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>Contact us<i class="ion-ios-arrow-forward"></i></span></p>
        </div>
      </div>
    </div>
  </section>

<section class="ftco-section ftco-no-pb contact-section">
    <div class="container">
        <center><h1>Create New Blog</h1> </center>
      <div class="row block-9">
        {% if error %}
          <script>
            alert("THIS USERNAME IS ALREADY EXIST...TRY ANOTHER.")
          </script>
        {% endif %}
        <div class="col-md-12 order-md-last d-flex">
          <form action="" class="bg-light p-5 contact-form" method="post" enctype="multipart/form-data">
              {% csrf_token %}
            

              <div class="form-group">
                    <select required class="form-control" name="cid">
                        <option  value="">Select Category</option>
                        {% for i in allcat %}
                            <option  value="{{ i.id }}">{{ i.name }}</option>
                        {% endfor %}
                    </select>
              </div>
              <div class="form-group">
                    <input type="text" required class="form-control" placeholder="Title" name="title">
              </div>

              <div class="form-group">
                    <input type="file" required class="form-control"  name="blogimg">
              </div>

              <div class="form-group">
                    <textarea placeholder="short Description" required class="form-control" name="short"></textarea>
              </div>

              <div class="form-group">
                    <textarea placeholder="Long Description" required class="form-control" name="long"></textarea>
              </div>

              <div class="form-group">
                    <input type="submit" value="Add Blog"  class="btn btn-primary py-3 px-5">
             </div>
          </form>
        
        </div>

        
      </div>
    </div>
  </section>
{% endblock %}

blogapp/templates/addblogmail.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Email</title>
    </head>
    <body>
        <h1>HELLO, {{ username }}</h1>
        <p>Your blog title is <h5> {{title}}</h5></p>
        <p>Description: {{ dec }}</p>

        <h6>Thanks & Regards</h6>
        <b>Jainesh</b>


        
    </body>
</html>

blogapp/templates/category_blog.html
<html>
  <head>
    <title>Blogger - Category Wise Blog</title>
  </head>
</html>
{% extends 'nav-footer.html'%}
	{% load static %}
	{% block sectionData %}

    <section class="hero-wrap hero-wrap-2" style="background-image: url({% static 'images/bg_4.jpg' %});">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-center">
          <div class="col-md-9 ftco-animate pb-5 text-center">
            <h1 class="mb-3 bread">{{ catedata.name }}</h1>
            <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'home' %}">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>{{ catedata.name }} <i class="ion-ios-arrow-forward"></i></span></p>
          </div>
        </div>
      </div>
    </section>


    <section class="ftco-section">
    	<div class="container">
        <div class="row">
        	<div class="col-lg-9">
        		<div class="row">
					{% for i in cateblog %}
        			<div class="col-md-4 ftco-animate">
    						<div class="blog-entry">
		    					<a href="{% url 'detail' i.id %}" class="img-2"><img src="{{ i.image.url }}" class="img-fluid" alt="Colorlib Template"></a>
			    				<div class="text pt-3">
	    							<p class="meta d-flex"><span class="pr-3">{{ i.usr.first_name }}</span><span class="ml-auto pl-3">{{ i.date }}</span></p>
	    							<h3><a href="{% url 'detail' i.id %}">{{ i.title }}</a></h3>
	    							<p class="mb-0"><a href="{% url 'detail' i.id %}" class="btn btn-black py-2">Read More <span class="icon-arrow_forward ml-4"></span></a></p>
	    						</div>
		    				</div>
    				</div>
					{% endfor %}
        		</div>
        		<div class="row mt-5">
		          <div class="col text-center">
		            <div class="block-27">
		              <ul>
		                <li><a href="#">&lt;</a></li>
		                <li class="active"><span>1</span></li>
		                <li><a href="#">2</a></li>
		                <li><a href="#">3</a></li>
		                <li><a href="#">4</a></li>
		                <li><a href="#">5</a></li>
		                <li><a href="#">&gt;</a></li>
		              </ul>
		            </div>
		          </div>
		        </div>
        	</div>

        	<div class="col-lg-3">
        		<div class="sidebar-box ftco-animate">
	        		<ul class="categories">
						<h3 class="heading mb-4">Categories</h3>
						{% for i in allcategory %}
						<li><a href="{% url 'cateblog' i.id %}">{{ i.name }}<span>({{ i.blogmodel_set.count }})</span></a></li>
						{% endfor %}
					  </ul>
	        		<div class="sidebar-box p-4 ftco-animate">
	              
	            </div>
	            
            </div>
        	</div>
        </div>
    	</div>
    </section>

		
		<section class="ftco-subscribe ftco-section bg-light">
      <div class="overlay">
        <div class="container">
          <div class="row d-flex justify-content-center">
            <div class="col-md-8 text-wrap text-center heading-section ftco-animate">
              <h2 class="mb-4"><span>Subcribe to our Newsletter</span></h2>
              <p>A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
              <div class="row d-flex justify-content-center mt-4 mb-4">
                <div class="col-md-8">
                  <form action="#" class="subscribe-form">
                    <div class="form-group d-flex">
                      <input type="text" class="form-control" placeholder="Enter email address">
                      <input type="submit" value="Subscribe" class="submit px-3">
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

{% endblock %}
    

blogapp/templates/changepassword.html
<html>
  <head>
    <title>Blogger - Change Password</title>
  </head>
</html>
{% extends 'nav-footer.html '%}
{% load static %}
{% block sectionData %}
<section class="hero-wrap hero-wrap-2" style="background-image: url({% static 'images/bg_4.jpg' %});">
    <div class="overlay"></div>
    <div class="container">
      <div class="row no-gutters slider-text align-items-end justify-content-center">
        <div class="col-md-9 ftco-animate pb-5 text-center">
          <h1 class="mb-3 bread">Change Password</h1>
          <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'home' %}">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>Change Password</span><i class="ion-ios-arrow-forward"></i></span></p>
        </div>
      </div>
    </div>
  </section>

<section class="ftco-section ftco-no-pb contact-section">
    <div class="container">
        <center><h1>Change Your Password</h1> </center>
      <div class="row block-9">
        
        <div class="col-md-12 order-md-last d-flex">
          <form action="" class="bg-light p-5 contact-form" method="post" enctype="multipart/form-data">
              {% csrf_token %}
                {% if error %}
                <p style="color: red;">Your Old Password Is Incorrect</p>
                {% endif %}
                <div class="form-group">
                    <input type="password" class="form-control" placeholder="Enter Your Old Password" name="oldpwd">
                </div>
                <div class="form-group">
                    <input type="password" required class="form-control" placeholder="Enter Your New Password" name="newpwd">
                </div>
            
                <div class="form-group">
                    <input type="submit" value="Change Password" class="btn btn-primary py-3 px-5">
                </div>
          </form>
        
        </div>

        
      </div>
    </div>
  </section>
{% endblock %}

blogapp/templates/mail_sending.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Email</title>
    </head>
    <body>
        <h1>Hello, {{ name }}</h1>
        <h5>Confirmation Mail</h5>
        <p>Thanks & Regards</p>
        <p>Jainesh</p>
    </body>
</html>

blogapp/templates/single.html
<html>
  <head>
    <title>Blogger - Blogdetail</title>
  </head>
</html>
{% extends 'nav-footer.html'%}
	{% load static %}
	{% block sectionData %}

    <section class="hero-wrap hero-wrap-2" style="background-image: url({% static 'images/bg_4.jpg' %});">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-center">
          <div class="col-md-9 ftco-animate pb-5 text-center">
            <h1 class="mb-3 bread">{{ blog.title}} -- {{ blog.category.name }}</h1>
            <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'home' %}">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>{{ blog.title }}<i class="ion-ios-arrow-forward"></i></span></p>
          </div>
        </div>
      </div>
    </section>

		<section class="ftco-section">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 order-lg-last ftco-animate">
            <h2 class="mb-3">{{ blog.title }}</h2>
            <a href="{% url 'like' blog.id %}"><P><button style="color: orange;" class="btn btn-primary btn-sm">{{ blog.likeblog_set.count }} Likes</button></P></a>
            <p>{{ blog.short }}</p>
            <p>
              <img src="{{ blog.image.url }}" alt="" class="img-fluid">
            </p>
            <p>{{ blog.long }}</p>
              
            
            <div class="about-author d-flex p-4 bg-light">
              <div class="bio mr-5">
                <img src="{{ user.userimage.url }}" alt="Image placeholder" class="img-fluid mb-4" height="100px" width="100px">
              </div>
              <div class="desc">
                <h3>{{ blog.usr.first_name }}</h3>
                <p>{{ user.aboutyou }}</p>
              </div>
            </div>


            <div class="pt-5 mt-5">
              <h3 class="mb-5">{{ blog.commentblog_set.count }} Comments</h3>
              <ul class="comment-list">
                {% for i in allcomments %}
                <li class="comment">
                  <div class="vcard bio">
                    <img src="{{ i.usr.userimage.url }}" alt="Image placeholder">
                  </div>
                  <div class="comment-body">
                    <h3>{{ i.usr.usr.first_name }}</h3>
                    <div class="meta">{{ i.commentdate }}</div>
                    <p>{{ i.comment }}</p>

                  </div>
                </li>
                {% endfor %}
              </ul>
              <!-- END comment-list -->
              {% if request.user.is_authenticated %}
              <div class="comment-form-wrap pt-5">
                <h3 class="mb-5">Leave a comment</h3>
                <form action="{% url 'comment' blog.id %}" class="p-5 bg-light" method="POST">
                  {% csrf_token %}
                  
                  <div class="form-group">
                    <label for="message">Comment</label>
                    <textarea name="comment" id="message" cols="30" rows="10" class="form-control"></textarea>
                  </div>
                  <div class="form-group">
                    <input type="submit" value="Post Comment" class="btn py-3 px-4 btn-primary">
                  </div>

                </form>
              </div>
              {% endif %}
            </div>

          </div> <!-- .col-md-8 -->
          <div class="col-lg-4 sidebar pr-lg-5 ftco-animate">
            <div class="sidebar-box">
              
            </div>
            <div class="sidebar-box ftco-animate">
              <ul class="categories">
                <h3 class="heading mb-4">Categories</h3>
                {% for i in allcategory %}
                <li><a href="{% url 'cateblog' i.id %}">{{ i.name }}<span>({{ i.blogmodel_set.count }})</span></a></li>
                {% endfor %}
              </ul>
            </div>

            <div class="sidebar-box ftco-animate">
              <h3 class="heading mb-4">Recent Blog</h3>
              <div class="block-21 mb-4 d-flex">
                <a class="blog-img mr-4" style="background-image: url(images/image_1.jpg);"></a>
                <div class="text">
                  <h3><a href="#">Even the all-powerful Pointing has no control about the blind texts</a></h3>
                  <div class="meta">
                    <div><a href="#"><span class="icon-calendar"></span> February 12, 2019</a></div>
                    <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                    <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                  </div>
                </div>
              </div>
              <div class="block-21 mb-4 d-flex">
                <a class="blog-img mr-4" style="background-image: url(images/image_2.jpg);"></a>
                <div class="text">
                  <h3><a href="#">Even the all-powerful Pointing has no control about the blind texts</a></h3>
                  <div class="meta">
                    <div><a href="#"><span class="icon-calendar"></span> February 12, 2019</a></div>
                    <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                    <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                  </div>
                </div>
              </div>
              <div class="block-21 mb-4 d-flex">
                <a class="blog-img mr-4" style="background-image: url(images/image_3.jpg);"></a>
                <div class="text">
                  <h3><a href="#">Even the all-powerful Pointing has no control about the blind texts</a></h3>
                  <div class="meta">
                    <div><a href="#"><span class="icon-calendar"></span> February 12, 2019</a></div>
                    <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                    <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                  </div>
                </div>
              </div>
            </div>

            <div class="sidebar-box ftco-animate">
              <h3 class="heading mb-4">Tag Cloud</h3>
              <div class="tagcloud">
                <a href="#" class="tag-cloud-link">dish</a>
                <a href="#" class="tag-cloud-link">menu</a>
                <a href="#" class="tag-cloud-link">food</a>
                <a href="#" class="tag-cloud-link">sweet</a>
                <a href="#" class="tag-cloud-link">tasty</a>
                <a href="#" class="tag-cloud-link">delicious</a>
                <a href="#" class="tag-cloud-link">desserts</a>
                <a href="#" class="tag-cloud-link">drinks</a>
              </div>
            </div>

            
          </div>

        </div>
      </div>
    </section> <!-- .section -->
		
		<section class="ftco-subscribe ftco-section bg-light">
      <div class="overlay">
        <div class="container">
          <div class="row d-flex justify-content-center">
            <div class="col-md-8 text-wrap text-center heading-section ftco-animate">
              <h2 class="mb-4"><span>Subcribe to our Newsletter</span></h2>
              <p>A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
              <div class="row d-flex justify-content-center mt-4 mb-4">
                <div class="col-md-8">
                  <form action="#" class="subscribe-form">
                    <div class="form-group d-flex">
                      <input type="text" class="form-control" placeholder="Enter email address">
                      <input type="submit" value="Subscribe" class="submit px-3">
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
{% endblock %}

    